//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprenticeTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApprenticeTbl()
        {
            this.CharacterizationConstraintApprenticeTbl = new HashSet<CharacterizationConstraintApprenticeTbl>();
            this.PreferenceApprenticeTbl = new HashSet<PreferenceApprenticeTbl>();
        }
    
        public int ApprenticeID { get; set; }
        public string ApprenticeName { get; set; }
        public Nullable<int> PlacementId { get; set; }
        public int AreaID { get; set; }
        public string Password { get; set; }
        public string ApprenticePhone { get; set; }
        public int CityId { get; set; }
        public decimal ApprenticeAga { get; set; }
    
        public virtual AreaTbl AreaTbl { get; set; }
        public virtual CityTbl CityTbl { get; set; }
        public virtual PlacementTbl PlacementTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CharacterizationConstraintApprenticeTbl> CharacterizationConstraintApprenticeTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreferenceApprenticeTbl> PreferenceApprenticeTbl { get; set; }
    }
}
