//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterizationConstraintsTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CharacterizationConstraintsTbl()
        {
            this.CharacterizationConstraintApprenticeTbl = new HashSet<CharacterizationConstraintApprenticeTbl>();
            this.TutorCharacterizationConstraintTbl = new HashSet<TutorCharacterizationConstraintTbl>();
        }
    
        public int CharacterizationConstraintsId { get; set; }
        public int ConstarintId { get; set; }
        public Nullable<bool> IsOpposit { get; set; }
        public string Value { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CharacterizationConstraintApprenticeTbl> CharacterizationConstraintApprenticeTbl { get; set; }
        public virtual ConstraintTbl ConstraintTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutorCharacterizationConstraintTbl> TutorCharacterizationConstraintTbl { get; set; }
    }
}
