//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstraintTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConstraintTbl()
        {
            this.CharacterizationConstraintsTbl = new HashSet<CharacterizationConstraintsTbl>();
        }
    
        public int ConstraintID { get; set; }
        public string ConstraintName { get; set; }
        public Nullable<int> Placement { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CharacterizationConstraintsTbl> CharacterizationConstraintsTbl { get; set; }
        public virtual PlacementTbl PlacementTbl { get; set; }
    }
}
