//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartMatchEntities : DbContext
    {
        public SmartMatchEntities()
            : base("name=SmartMatchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApprenticeTbl> ApprenticeTbl { get; set; }
        public virtual DbSet<AreaTbl> AreaTbl { get; set; }
        public virtual DbSet<CharacterizationConstraintApprenticeTbl> CharacterizationConstraintApprenticeTbl { get; set; }
        public virtual DbSet<CharacterizationConstraintsTbl> CharacterizationConstraintsTbl { get; set; }
        public virtual DbSet<CityTbl> CityTbl { get; set; }
        public virtual DbSet<ConstraintTbl> ConstraintTbl { get; set; }
        public virtual DbSet<PattrenConstaraintTbl> PattrenConstaraintTbl { get; set; }
        public virtual DbSet<PlacementTbl> PlacementTbl { get; set; }
        public virtual DbSet<PreferenceApprenticeTbl> PreferenceApprenticeTbl { get; set; }
        public virtual DbSet<PreferenceTbl> PreferenceTbl { get; set; }
        public virtual DbSet<PreferenceTutorTbl> PreferenceTutorTbl { get; set; }
        public virtual DbSet<TutorCharacterizationConstraintTbl> TutorCharacterizationConstraintTbl { get; set; }
        public virtual DbSet<TutorForApprenticeTbl> TutorForApprenticeTbl { get; set; }
        public virtual DbSet<TutorTbl> TutorTbl { get; set; }
        public virtual DbSet<UserTbl> UserTbl { get; set; }
    }
}
