//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorCharacterizationConstraintTbl
    {
        public int TutorCharacterizationConstraintId { get; set; }
        public int CharacterizationConstarintId { get; set; }
        public int TutorId { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual CharacterizationConstraintsTbl CharacterizationConstraintsTbl { get; set; }
        public virtual TutorTbl TutorTbl { get; set; }
    }
}
