//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorForApprenticeTbl
    {
        public int TutorForApprenticeId { get; set; }
        public Nullable<int> PlacementID { get; set; }
        public Nullable<int> TutorID { get; set; }
        public Nullable<int> ApprenticeID { get; set; }
        public Nullable<int> MatchLevelScore { get; set; }
    
        public virtual PlacementTbl PlacementTbl { get; set; }
        public virtual PlacementTbl PlacementTbl1 { get; set; }
        public TutorForApprenticeTbl()
        {

        }
        public TutorForApprenticeTbl(TutorForApprenticeTbl t)
        {
            this.TutorForApprenticeId = t.TutorForApprenticeId;
            this.ApprenticeID = t.ApprenticeID;
            this.TutorID = t.TutorID;
            this.PlacementID = t.PlacementID;
            this.MatchLevelScore = t.MatchLevelScore;
        }
    }
}
