//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TutorTbl()
        {
            this.PreferenceTutorTbl = new HashSet<PreferenceTutorTbl>();
            this.TutorCharacterizationConstraintTbl = new HashSet<TutorCharacterizationConstraintTbl>();
        }
    
        public int TutorID { get; set; }
        public int PlacementId { get; set; }
        public string TutorName { get; set; }
        public Nullable<decimal> TutorAge { get; set; }
        public string TutorPhone { get; set; }
        public int AreaID { get; set; }
        public string PasswordID { get; set; }
        public int CityId { get; set; }
    
        public virtual AreaTbl AreaTbl { get; set; }
        public virtual CityTbl CityTbl { get; set; }
        public virtual CityTbl CityTbl1 { get; set; }
        public virtual PlacementTbl PlacementTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreferenceTutorTbl> PreferenceTutorTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutorCharacterizationConstraintTbl> TutorCharacterizationConstraintTbl { get; set; }
    }
}
